version: '3.3'
services:
  d3aiDatabase:
    image: mysql:latest
    container_name: d3ai_mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: d3ai
      MYSQL_ROOT_PASSWORD: kirk8242
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sharedDatabase

  d3ai:
    image: d3ai:latest
    ports:
      - "3002:3002"
    environment:
      MYSQL_DATABASE: d3ai
      MYSQL_PORT: 3306  
      MYSQL_USER: root
      MYSQL_PASSWORD: kirk8242
      MYSQL_HOST: d3aiDatabase
      PORT: 3002
      NODE_ENV: production
    depends_on:
      - d3aiDatabase
    networks:
      - sharedDatabase

networks:
  sharedDatabase:
    name: sharedDatabase
    attachable: true

volumes:
  mysql_data: