version: '3.3'
services:
  d3ai:
    image: d3ai:latest
    ports:
      - "3002:3002"
    environment:
      MYSQL_DATABASE: d3ai   # Points to a different database in the shared MySQL instance
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: kirk824
      MYSQL_HOST: jatDatabase  # Uses the external MySQL container from jobdlink
      PORT: 3002
      NODE_ENV: production
    networks:
      - sharedDatabase

networks:
  sharedDatabase:
    external: true   # Reference to the external network