version: '3.3'
services:
  d3aiDatabase:
    image: mysql:latest
    container_name: d3ai_mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: d3ai
      MYSQL_ROOT_PASSWORD: kirk8242
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
  jobdlink:
    image: d3ai:latest
    ports:
      - "3002:3002"
    environment:
      MYSQL_DATABASE: d3ai
      MYSQL_PORT: 3307
      MYSQL_USER: root
      MYSQL_PASSWORD: kirk8242
      MYSQL_HOST: d3aiDatabase
      PORT: 3002
      NODE_ENV: production
    depends_on:
      - d3aiDatabase

volumes:
  mysql_data:
